company:
  name: Quart Ciphers

spring:
  application:
    name: SERVICE-DISCOVERY
  profiles:
    active: ${PROFILE:local}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
