company:
  name: Quart Ciphers

spring:
  application:
    name: SERVICE-DISCOVERY
  profiles:
    active: ${PROFILE}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  password: ${EUREKA_USER_PASSWORD}
  instance:
    hostname: localhost

security:
  user:
    password: ${eureka.password}